use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "Vernieuwen",
    update_frequency: "Updatefrequentie",
    one_minute: "1 minuut",
    five_minutes: "5 minuten",
    fifteen_minutes: "15 minuten",
    one_hour: "1 uur",
    models: "Modellen",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Instellingen",
    start_with_windows: "Opstarten met Windows",
    reset_position: "Positie herstellen",
    language: "Taal",
    system_default: "Systeemstandaard",
    monitor: "Monitor",
    about: "Over",
    about_message: "Claude Counter\nGemaakt door faga12@gmail.com\nGebouwd met behulp van Claude (Anthropic)\n\nGebaseerd op het opensource-project Claude-Code-Usage-Monitor (MIT-licentie).",
    session_limit_line: "5-uurslimiet op {pct}%, reset over {time}",
    weekly_limit_line: "Wekelijkse limiet op {pct}%, reset over {time}",
    day_word_singular: "dag",
    day_word_plural: "dagen",
    exit: "Afsluiten",
    show_widget: "Widget tonen",
    session_window: "5u",
    weekly_window: "7d",
    now: "nu",
    day_suffix: "d",
    hour_suffix: "u",
    minute_suffix: "m",
    token_expired_title: "Claude Code-authenticatiefout",
    token_expired_body: "Voer 'claude' uit in een terminal, gebruik daarna '/login' en volg de stappen. Ververs of herstart de app daarna.",
    codex_token_expired_title: "Codex-authenticatiefout",
    codex_token_expired_body: "Voer 'codex' uit in een terminal en volg de aanmeldstappen. Ververs of herstart de app daarna.",
    antigravity_token_expired_title: "Antigravity-authenticatiefout",
    antigravity_token_expired_body: "Open Antigravity en meld je opnieuw aan. Ververs of herstart de app daarna.",
    no_credentials_title: "Claude Code instellen",
    no_credentials_body: "Er zijn geen Claude Code-gegevens gevonden. Volg deze stappen:\n\n1. Open PowerShell.\n2. Plak het installatiecommando (al gekopieerd naar je klembord — druk gewoon op Ctrl+V) en druk op Enter.\n3. Voer uit: claude\n4. Volg de aanmeldstappen (gebruik /login als dit niet automatisch wordt gevraagd).\n5. Open deze app opnieuw.",
    codex_no_credentials_title: "Codex instellen",
    codex_no_credentials_body: "Er zijn geen Codex-gegevens gevonden. Volg deze stappen:\n\n1. Installeer de Codex CLI als je dat nog niet hebt gedaan.\n2. Open een terminal en voer uit: codex\n3. Volg de aanmeldstappen.\n4. Open deze app opnieuw.",
    antigravity_no_credentials_title: "Antigravity instellen",
    antigravity_no_credentials_body: "Er zijn geen Antigravity-gegevens gevonden. Volg deze stappen:\n\n1. Open (of installeer) Antigravity.\n2. Meld je aan met je account.\n3. Open deze app opnieuw.",
    codex_window_title: "Codex-gebruiksmonitor",
    antigravity_window_title: "Antigravity-gebruiksmonitor",
    second_suffix: "s",
};
