use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    models: "Models",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Settings",
    start_with_windows: "Start with Windows",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    monitor: "Monitor",
    about: "About",
    about_message: "Claude Counter\nCreated by faga12@gmail.com\nBuilt with the help of Claude (Anthropic)\n\nBased on the open-source project Claude-Code-Usage-Monitor (MIT License).",
    session_limit_line: "5-hour limit at {pct}%, resets in {time}",
    weekly_limit_line: "Weekly limit at {pct}%, resets in {time}",
    day_word_singular: "day",
    day_word_plural: "days",
    exit: "Exit",
    show_widget: "Show Widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Claude Code Auth Error",
    token_expired_body: "Run 'claude' in a terminal, then use '/login' and follow the prompts. After that, refresh or restart this app.",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    antigravity_token_expired_title: "Antigravity Auth Error",
    antigravity_token_expired_body: "Open Antigravity and sign in again. After that, refresh or restart this app.",
    no_credentials_title: "Set up Claude Code",
    no_credentials_body: "No Claude Code credentials were found. Follow these steps:\n\n1. Open PowerShell.\n2. Paste the install command (already copied to your clipboard - just press Ctrl+V) and press Enter.\n3. Run: claude\n4. Follow the sign-in prompts (use /login if it doesn't ask automatically).\n5. Reopen this app.",
    codex_no_credentials_title: "Set up Codex",
    codex_no_credentials_body: "No Codex credentials were found. Follow these steps:\n\n1. Install the Codex CLI if you haven't already.\n2. Open a terminal and run: codex\n3. Follow the sign-in prompts.\n4. Reopen this app.",
    antigravity_no_credentials_title: "Set up Antigravity",
    antigravity_no_credentials_body: "No Antigravity credentials were found. Follow these steps:\n\n1. Open (or install) Antigravity.\n2. Sign in with your account.\n3. Reopen this app.",
    codex_window_title: "Codex Usage Monitor",
    antigravity_window_title: "Antigravity Usage Monitor",
    second_suffix: "s",
};
