use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "Actualiser",
    update_frequency: "Fréquence de mise à jour",
    one_minute: "1 minute",
    five_minutes: "5 minutes",
    fifteen_minutes: "15 minutes",
    one_hour: "1 heure",
    models: "Modeles",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Paramètres",
    start_with_windows: "Démarrer avec Windows",
    reset_position: "Réinitialiser la position",
    language: "Langue",
    system_default: "Par défaut du système",
    monitor: "Écran",
    about: "À propos",
    about_message: "Claude Counter\nCréé par faga12@gmail.com\nDéveloppé avec l'aide de Claude (Anthropic)\n\nBasé sur le projet open source Claude-Code-Usage-Monitor (licence MIT).",
    session_limit_line: "Limite de 5 heures à {pct}%, réinitialise dans {time}",
    weekly_limit_line: "Limite hebdomadaire à {pct}%, réinitialise dans {time}",
    day_word_singular: "jour",
    day_word_plural: "jours",
    exit: "Quitter",
    show_widget: "Afficher le widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "maintenant",
    day_suffix: "j",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Erreur d'authentification",
    token_expired_body: "Exécutez 'claude' dans un terminal, puis utilisez '/login' et suivez les instructions. Ensuite, actualisez ou redémarrez cette application.",
    codex_token_expired_title: "Erreur d'authentification Codex",
    codex_token_expired_body: "Executez 'codex' dans un terminal et suivez les instructions de connexion. Ensuite, actualisez ou redemarrez cette application.",
    antigravity_token_expired_title: "Erreur d'authentification Antigravity",
    antigravity_token_expired_body: "Ouvrez Antigravity et reconnectez-vous. Ensuite, actualisez ou redemarrez cette application.",
    no_credentials_title: "Configurer Claude Code",
    no_credentials_body: "Aucun identifiant Claude Code n'a ete trouve. Suivez ces etapes :\n\n1. Ouvrez PowerShell.\n2. Collez la commande d'installation (deja copiee dans le presse-papiers — appuyez simplement sur Ctrl+V) puis sur Entree.\n3. Executez : claude\n4. Suivez les instructions de connexion (utilisez /login si ce n'est pas demande automatiquement).\n5. Rouvrez cette application.",
    codex_no_credentials_title: "Configurer Codex",
    codex_no_credentials_body: "Aucun identifiant Codex n'a ete trouve. Suivez ces etapes :\n\n1. Installez la CLI Codex si ce n'est pas deja fait.\n2. Ouvrez un terminal et executez : codex\n3. Suivez les instructions de connexion.\n4. Rouvrez cette application.",
    antigravity_no_credentials_title: "Configurer Antigravity",
    antigravity_no_credentials_body: "Aucun identifiant Antigravity n'a ete trouve. Suivez ces etapes :\n\n1. Ouvrez (ou installez) Antigravity.\n2. Connectez-vous avec votre compte.\n3. Rouvrez cette application.",
    codex_window_title: "Moniteur d'utilisation Codex",
    antigravity_window_title: "Moniteur d'utilisation Antigravity",
    second_suffix: "s",
};
