use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "Aktualisieren",
    update_frequency: "Aktualisierungsintervall",
    one_minute: "1 Minute",
    five_minutes: "5 Minuten",
    fifteen_minutes: "15 Minuten",
    one_hour: "1 Stunde",
    models: "Modelle",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Einstellungen",
    start_with_windows: "Mit Windows starten",
    reset_position: "Position zurücksetzen",
    language: "Sprache",
    system_default: "Systemstandard",
    monitor: "Monitor",
    about: "Über",
    about_message: "Claude Counter\nErstellt von faga12@gmail.com\nMit Hilfe von Claude (Anthropic) entwickelt\n\nBasierend auf dem Open-Source-Projekt Claude-Code-Usage-Monitor (MIT-Lizenz).",
    session_limit_line: "5-Stunden-Limit bei {pct}%, Zurücksetzung in {time}",
    weekly_limit_line: "Wochenlimit bei {pct}%, Zurücksetzung in {time}",
    day_word_singular: "Tag",
    day_word_plural: "Tage",
    exit: "Beenden",
    show_widget: "Widget anzeigen",
    session_window: "5h",
    weekly_window: "7d",
    now: "jetzt",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Authentifizierungsfehler",
    token_expired_body: "Führen Sie 'claude' in einem Terminal aus, verwenden Sie dann '/login' und folgen Sie den Anweisungen. Aktualisieren oder starten Sie diese App anschließend neu.",
    codex_token_expired_title: "Codex-Authentifizierungsfehler",
    codex_token_expired_body: "Fuhren Sie 'codex' in einem Terminal aus und folgen Sie den Anmeldeanweisungen. Aktualisieren oder starten Sie diese App anschliessend neu.",
    antigravity_token_expired_title: "Antigravity-Authentifizierungsfehler",
    antigravity_token_expired_body: "Offnen Sie Antigravity und melden Sie sich erneut an. Aktualisieren oder starten Sie diese App anschliessend neu.",
    no_credentials_title: "Claude Code einrichten",
    no_credentials_body: "Es wurden keine Claude Code-Anmeldedaten gefunden. Folgen Sie diesen Schritten:\n\n1. Offnen Sie PowerShell.\n2. Fugen Sie den Installationsbefehl ein (bereits in die Zwischenablage kopiert — druecken Sie einfach Strg+V) und druecken Sie Enter.\n3. Fuhren Sie aus: claude\n4. Folgen Sie den Anmeldeanweisungen (verwenden Sie /login, falls nicht automatisch abgefragt).\n5. Offnen Sie diese App erneut.",
    codex_no_credentials_title: "Codex einrichten",
    codex_no_credentials_body: "Es wurden keine Codex-Anmeldedaten gefunden. Folgen Sie diesen Schritten:\n\n1. Installieren Sie die Codex-CLI, falls noch nicht geschehen.\n2. Offnen Sie ein Terminal und fuhren Sie aus: codex\n3. Folgen Sie den Anmeldeanweisungen.\n4. Offnen Sie diese App erneut.",
    antigravity_no_credentials_title: "Antigravity einrichten",
    antigravity_no_credentials_body: "Es wurden keine Antigravity-Anmeldedaten gefunden. Folgen Sie diesen Schritten:\n\n1. Offnen (oder installieren) Sie Antigravity.\n2. Melden Sie sich mit Ihrem Konto an.\n3. Offnen Sie diese App erneut.",
    codex_window_title: "Codex-Nutzungsmonitor",
    antigravity_window_title: "Antigravity-Nutzungsmonitor",
    second_suffix: "s",
};
