use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "更新",
    update_frequency: "更新間隔",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    models: "モデル",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "Windows と同時に開始",
    reset_position: "位置をリセット",
    language: "言語",
    system_default: "システム既定",
    monitor: "モニター",
    about: "このアプリについて",
    about_message: "Claude Counter\n作成者: faga12@gmail.com\nClaude (Anthropic) の助けを借りて開発\n\nオープンソースプロジェクト Claude-Code-Usage-Monitor (MITライセンス) をベースにしています。",
    session_limit_line: "5時間制限 {pct}%、{time}でリセット",
    weekly_limit_line: "週間制限 {pct}%、{time}でリセット",
    day_word_singular: "日",
    day_word_plural: "日",
    exit: "終了",
    show_widget: "ウィジェットを表示",
    session_window: "5h",
    weekly_window: "7d",
    now: "今",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    token_expired_title: "認証エラー",
    token_expired_body: "ターミナルで 'claude' を実行し、'/login' を使って案内に従ってください。その後、このアプリを更新するか再起動してください。",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "ターミナルで 'codex' を実行し、サインインの案内に従ってください。その後、このアプリを更新または再起動してください。",
    antigravity_token_expired_title: "Antigravity 認証エラー",
    antigravity_token_expired_body: "Antigravity を開いて再度サインインしてください。その後、このアプリを更新するか再起動してください。",
    no_credentials_title: "Claude Code を設定",
    no_credentials_body: "Claude Code の認証情報が見つかりませんでした。次の手順に従ってください：\n\n1. PowerShell を開く。\n2. インストールコマンドを貼り付け（すでにクリップボードにコピー済み — Ctrl+V を押すだけ）て Enter を押す。\n3. 実行: claude\n4. 案内に従ってサインインする（自動で聞かれない場合は /login を使う）。\n5. このアプリを再度開く。",
    codex_no_credentials_title: "Codex を設定",
    codex_no_credentials_body: "Codex の認証情報が見つかりませんでした。次の手順に従ってください：\n\n1. まだの場合は Codex CLI をインストールする。\n2. ターミナルを開いて実行: codex\n3. サインインの案内に従う。\n4. このアプリを再度開く。",
    antigravity_no_credentials_title: "Antigravity を設定",
    antigravity_no_credentials_body: "Antigravity の認証情報が見つかりませんでした。次の手順に従ってください：\n\n1. Antigravity を開く（または インストールする）。\n2. アカウントでサインインする。\n3. このアプリを再度開く。",
    codex_window_title: "Codex 使用量モニター",
    antigravity_window_title: "Antigravity 使用量モニター",
    second_suffix: "秒",
};
