use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "새로고침",
    update_frequency: "업데이트 주기",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    models: "모델",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "설정",
    start_with_windows: "Windows 시작 시 자동 실행",
    reset_position: "위치 초기화",
    language: "언어",
    system_default: "시스템 기본값",
    monitor: "모니터",
    about: "정보",
    about_message: "Claude Counter\n제작: faga12@gmail.com\nClaude (Anthropic)의 도움으로 제작되었습니다\n\n오픈소스 프로젝트 Claude-Code-Usage-Monitor (MIT 라이선스)를 기반으로 합니다.",
    session_limit_line: "5시간 한도 {pct}%, {time} 후 초기화",
    weekly_limit_line: "주간 한도 {pct}%, {time} 후 초기화",
    day_word_singular: "일",
    day_word_plural: "일",
    exit: "종료",
    show_widget: "위젯 표시",
    session_window: "5시간",
    weekly_window: "7일",
    now: "지금",
    day_suffix: "일",
    hour_suffix: "시간",
    minute_suffix: "분",
    token_expired_title: "인증 오류",
    token_expired_body: "터미널에서 'claude'를 실행한 다음 '/login'을 사용하고 안내에 따라 진행하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "터미널에서 'codex'를 실행하고 로그인 안내를 따르세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    antigravity_token_expired_title: "Antigravity 인증 오류",
    antigravity_token_expired_body: "Antigravity를 열고 다시 로그인하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    no_credentials_title: "Claude Code 설정",
    no_credentials_body: "Claude Code 인증 정보를 찾을 수 없습니다. 다음 단계를 따르세요:\n\n1. PowerShell을 엽니다.\n2. 설치 명령어를 붙여넣고 (이미 클립보드에 복사됨 — Ctrl+V만 누르면 됩니다) Enter를 누르세요.\n3. 실행: claude\n4. 안내에 따라 로그인하세요 (자동으로 묻지 않으면 /login 사용).\n5. 이 앱을 다시 여세요.",
    codex_no_credentials_title: "Codex 설정",
    codex_no_credentials_body: "Codex 인증 정보를 찾을 수 없습니다. 다음 단계를 따르세요:\n\n1. 아직 설치하지 않았다면 Codex CLI를 설치하세요.\n2. 터미널을 열고 실행: codex\n3. 로그인 안내를 따르세요.\n4. 이 앱을 다시 여세요.",
    antigravity_no_credentials_title: "Antigravity 설정",
    antigravity_no_credentials_body: "Antigravity 인증 정보를 찾을 수 없습니다. 다음 단계를 따르세요:\n\n1. Antigravity를 여세요 (또는 설치하세요).\n2. 계정으로 로그인하세요.\n3. 이 앱을 다시 여세요.",
    codex_window_title: "Codex 사용량 모니터",
    antigravity_window_title: "Antigravity 사용량 모니터",
    second_suffix: "초",
};
