use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "Обновить",
    update_frequency: "Частота обновления",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    models: "Модели",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Настройки",
    start_with_windows: "Запускать вместе с Windows",
    reset_position: "Сбросить позицию",
    language: "Язык",
    system_default: "Системный по умолчанию",
    monitor: "Монитор",
    about: "О программе",
    about_message: "Claude Counter\nСоздано: faga12@gmail.com\nРазработано с помощью Claude (Anthropic)\n\nНа основе проекта с открытым исходным кодом Claude-Code-Usage-Monitor (лицензия MIT).",
    session_limit_line: "Лимит 5 часов: {pct}%, сброс через {time}",
    weekly_limit_line: "Недельный лимит: {pct}%, сброс через {time}",
    day_word_singular: "день",
    day_word_plural: "дней",
    exit: "Выход",
    show_widget: "Показать виджет",
    session_window: "5ч",
    weekly_window: "7д",
    now: "сейчас",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    token_expired_title: "Ошибка авторизации Claude Code",
    token_expired_body: "Запустите 'claude' в терминале, затем используйте '/login' и следуйте инструкциям. После этого обновите или перезапустите приложение.",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Запустите 'codex' в терминале и следуйте инструкциям для входа. После этого обновите или перезапустите приложение.",
    antigravity_token_expired_title: "Ошибка авторизации Antigravity",
    antigravity_token_expired_body: "Откройте Antigravity и войдите снова. После этого обновите или перезапустите приложение.",
    no_credentials_title: "Настройка Claude Code",
    no_credentials_body: "Учётные данные Claude Code не найдены. Выполните следующие шаги:\n\n1. Откройте PowerShell.\n2. Вставьте команду установки (уже скопирована в буфер обмена — просто нажмите Ctrl+V) и нажмите Enter.\n3. Выполните: claude\n4. Следуйте инструкциям для входа (используйте /login, если не предложено автоматически).\n5. Откройте приложение снова.",
    codex_no_credentials_title: "Настройка Codex",
    codex_no_credentials_body: "Учётные данные Codex не найдены. Выполните следующие шаги:\n\n1. Установите Codex CLI, если ещё не сделали этого.\n2. Откройте терминал и выполните: codex\n3. Следуйте инструкциям для входа.\n4. Откройте приложение снова.",
    antigravity_no_credentials_title: "Настройка Antigravity",
    antigravity_no_credentials_body: "Учётные данные Antigravity не найдены. Выполните следующие шаги:\n\n1. Откройте (или установите) Antigravity.\n2. Войдите в свою учётную запись.\n3. Откройте приложение снова.",
    codex_window_title: "Монитор использования Codex",
    antigravity_window_title: "Монитор использования Antigravity",
};
