use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "Actualizar",
    update_frequency: "Frecuencia de actualización",
    one_minute: "1 minuto",
    five_minutes: "5 minutos",
    fifteen_minutes: "15 minutos",
    one_hour: "1 hora",
    models: "Modelos",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configuración",
    start_with_windows: "Iniciar con Windows",
    reset_position: "Restablecer posición",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    monitor: "Monitor",
    about: "Acerca de",
    about_message: "Claude Counter\nCreado por faga12@gmail.com\nConstruido con la ayuda de Claude (Anthropic)\n\nBasado en el proyecto de código abierto Claude-Code-Usage-Monitor (Licencia MIT).",
    session_limit_line: "Límite de 5 horas al {pct}%, se reinicia en {time}",
    weekly_limit_line: "Límite semanal al {pct}%, se reinicia en {time}",
    day_word_singular: "día",
    day_word_plural: "días",
    exit: "Salir",
    show_widget: "Mostrar widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "ahora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Error de autenticación",
    token_expired_body: "Ejecuta 'claude' en una terminal, luego usa '/login' y sigue las indicaciones. Después, actualiza o reinicia esta aplicación.",
    codex_token_expired_title: "Error de autenticacion de Codex",
    codex_token_expired_body: "Ejecuta 'codex' en una terminal y sigue las indicaciones de inicio de sesion. Despues, actualiza o reinicia esta aplicacion.",
    antigravity_token_expired_title: "Error de autenticacion de Antigravity",
    antigravity_token_expired_body: "Abre Antigravity e inicia sesion otra vez. Despues, actualiza o reinicia esta aplicacion.",
    no_credentials_title: "Configura Claude Code",
    no_credentials_body: "No se encontraron credenciales de Claude Code. Sigue estos pasos:\n\n1. Abre PowerShell.\n2. Pega el comando de instalacion (ya copiado en tu portapapeles, solo presiona Ctrl+V) y presiona Enter.\n3. Ejecuta: claude\n4. Sigue las indicaciones para iniciar sesion (usa /login si no te lo pide automaticamente).\n5. Vuelve a abrir esta aplicacion.",
    codex_no_credentials_title: "Configura Codex",
    codex_no_credentials_body: "No se encontraron credenciales de Codex. Sigue estos pasos:\n\n1. Instala la CLI de Codex si aun no la tienes.\n2. Abre una terminal y ejecuta: codex\n3. Sigue las indicaciones de inicio de sesion.\n4. Vuelve a abrir esta aplicacion.",
    antigravity_no_credentials_title: "Configura Antigravity",
    antigravity_no_credentials_body: "No se encontraron credenciales de Antigravity. Sigue estos pasos:\n\n1. Abre (o instala) Antigravity.\n2. Inicia sesion con tu cuenta.\n3. Vuelve a abrir esta aplicacion.",
    codex_window_title: "Monitor de uso de Codex",
    antigravity_window_title: "Monitor de uso de Antigravity",
    second_suffix: "s",
};
