use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Counter",
    refresh: "重新整理",
    update_frequency: "更新頻率",
    one_minute: "1 分鐘",
    five_minutes: "5 分鐘",
    fifteen_minutes: "15 分鐘",
    one_hour: "1 小時",
    models: "模型",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "開機時啟動",
    reset_position: "重置位置",
    language: "語言",
    system_default: "系統預設",
    monitor: "顯示器",
    about: "關於",
    about_message: "Claude Counter\n作者：faga12@gmail.com\n在 Claude (Anthropic) 的協助下開發\n\n基於開源專案 Claude-Code-Usage-Monitor (MIT 授權)。",
    session_limit_line: "5小時上限 {pct}%，{time}後重置",
    weekly_limit_line: "每週上限 {pct}%，{time}後重置",
    day_word_singular: "天",
    day_word_plural: "天",
    exit: "結束",
    show_widget: "顯示小工具",
    session_window: "5h",
    weekly_window: "7d",
    now: "現在",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    token_expired_title: "驗證錯誤",
    token_expired_body: "請在終端機中執行 'claude'，然後使用 '/login' 並依照提示操作。完成後，請重新整理或重新啟動此應用程式。",
    codex_token_expired_title: "Codex 驗證錯誤",
    codex_token_expired_body: "請在終端機中執行 'codex'，並依照登入提示操作。完成後，請重新整理或重新啟動此應用程式。",
    antigravity_token_expired_title: "Antigravity 驗證錯誤",
    antigravity_token_expired_body: "請開啟 Antigravity 並重新登入。完成後，請重新整理或重新啟動此應用程式。",
    no_credentials_title: "設定 Claude Code",
    no_credentials_body: "找不到 Claude Code 憑證。請依照下列步驟操作：\n\n1. 開啟 PowerShell。\n2. 貼上安裝指令（已複製到剪貼簿，只需按 Ctrl+V）後按 Enter。\n3. 執行：claude\n4. 依照提示登入（若未自動詢問，請使用 /login）。\n5. 重新開啟此應用程式。",
    codex_no_credentials_title: "設定 Codex",
    codex_no_credentials_body: "找不到 Codex 憑證。請依照下列步驟操作：\n\n1. 若尚未安裝，請安裝 Codex CLI。\n2. 開啟終端機並執行：codex\n3. 依照登入提示操作。\n4. 重新開啟此應用程式。",
    antigravity_no_credentials_title: "設定 Antigravity",
    antigravity_no_credentials_body: "找不到 Antigravity 憑證。請依照下列步驟操作：\n\n1. 開啟（或安裝）Antigravity。\n2. 使用您的帳號登入。\n3. 重新開啟此應用程式。",
    codex_window_title: "Codex 使用量監控",
    antigravity_window_title: "Antigravity 使用量監控",
    second_suffix: "秒",
};
